apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
data:
  PRIME_USER_WEIGHT: "10"
  TEXT_USER_WEIGHT: "0"
  PRIME_RANGE_INTERVAL: "2.0"
  PRIME_KTH_INTERVAL: "2.0"
  PRIME_CHECK_INTERVAL: "2.0"
  PRIME_RANGE_MIN: "1000"
  PRIME_RANGE_MAX: "500000"
  PRIME_KTH_MIN: "1000"
  PRIME_KTH_MAX: "50000"
  PRIME_CHECK_MIN: "5000000"
  PRIME_CHECK_MAX: "100000000"
