apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 1 # Scale this as needed
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: locust-test:v1
          imagePullPolicy: Never
          args: ["-f", "/mnt/locust/locustfile.py", "--worker", "--master-host=locust-master"]
          env: 
            - name: PRIME_USER_WEIGHT
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_USER_WEIGHT
            - name: PRIME_RANGE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_RANGE_INTERVAL
            - name: PRIME_RANGE_MIN
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_RANGE_MIN
            - name: PRIME_RANGE_MAX
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_RANGE_MAX
            - name: PRIME_KTH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_KTH_INTERVAL
            - name: PRIME_KTH_MIN
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_KTH_MIN
            - name: PRIME_KTH_MAX
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_KTH_MAX
            - name: PRIME_CHECK_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_CHECK_INTERVAL
            - name: PRIME_CHECK_MIN
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_CHECK_MIN
            - name: PRIME_CHECK_MAX
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: PRIME_CHECK_MAX
            - name: TEXT_USER_WEIGHT
              valueFrom:
                configMapKeyRef:
                  name: locust-config
                  key: TEXT_USER_WEIGHT
