name: predictive-autoscaling-k8s-test
services:
  prime-service:
    build: ./services/prime-service
    container_name: prime-service-test
    ports:
      - "3000:3000"
  text-service:
    build: ./services/text-service
    container_name: text-service-test
    ports:
      - "3001:3000"

  frontend:
    build: ./services/frontend
    container_name: frontend-test
    ports:
      - "8080:80"
    depends_on:
      - prime-service
      - text-service

  locust:
    build:
      context: ./locust-test
      dockerfile: Dockerfile
    container_name: locust
    env_file:
      - ./locust-test/locust.env
    ports:
      - "8089:8089"
    volumes:
      - ./shares:/mnt/shares
    entrypoint:
      - sh
      - /mnt/locust/start-locust.sh

  custom-load-test:
    build:
      context: ./custom-load-test
      dockerfile: Dockerfile
    container_name: custom-load-test
    env_file:
      - ./custom-load-test/custom_load_test.env
    volumes:
      - ./shares:/mnt/shares

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      # Gắn file cấu hình ở Bước 2 vào container
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      # Lưu trữ dữ liệu lịch sử để không bị mất khi tắt máy
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "2999:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  ai-model:
    build: ./ai-model
    container_name: ai-model
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    volumes:
      - ./ai-model/data:/app/data

volumes:
  prometheus_data:
  grafana_data:
