//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomScaler) DeepCopyInto(out *CustomScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomScaler.
func (in *CustomScaler) DeepCopy() *CustomScaler {
	if in == nil {
		return nil
	}
	out := new(CustomScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomScalerList) DeepCopyInto(out *CustomScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomScalerList.
func (in *CustomScalerList) DeepCopy() *CustomScalerList {
	if in == nil {
		return nil
	}
	out := new(CustomScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomScalerSpec) DeepCopyInto(out *CustomScalerSpec) {
	*out = *in
	if in.SafeRPSPerPod != nil {
		in, out := &in.SafeRPSPerPod, &out.SafeRPSPerPod
		*out = new(float64)
		**out = **in
	}
	if in.SafetyFactor != nil {
		in, out := &in.SafetyFactor, &out.SafetyFactor
		*out = new(float64)
		**out = **in
	}
	if in.SparePod != nil {
		in, out := &in.SparePod, &out.SparePod
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.WorkerPrototype != nil {
		in, out := &in.WorkerPrototype, &out.WorkerPrototype
		*out = new(WorkerPrototypeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomScalerSpec.
func (in *CustomScalerSpec) DeepCopy() *CustomScalerSpec {
	if in == nil {
		return nil
	}
	out := new(CustomScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomScalerStatus) DeepCopyInto(out *CustomScalerStatus) {
	*out = *in
	if in.WorkerPrototype != nil {
		in, out := &in.WorkerPrototype, &out.WorkerPrototype
		*out = new(WorkerPrototypeStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomScalerStatus.
func (in *CustomScalerStatus) DeepCopy() *CustomScalerStatus {
	if in == nil {
		return nil
	}
	out := new(CustomScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerOperationStatus) DeepCopyInto(out *WorkerOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CommandFinishedAt != nil {
		in, out := &in.CommandFinishedAt, &out.CommandFinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerOperationStatus.
func (in *WorkerOperationStatus) DeepCopy() *WorkerOperationStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPrototypeSpec) DeepCopyInto(out *WorkerPrototypeSpec) {
	*out = *in
	if in.TargetWorkerCount != nil {
		in, out := &in.TargetWorkerCount, &out.TargetWorkerCount
		*out = new(int32)
		**out = **in
	}
	if in.MaxBatchSize != nil {
		in, out := &in.MaxBatchSize, &out.MaxBatchSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPrototypeSpec.
func (in *WorkerPrototypeSpec) DeepCopy() *WorkerPrototypeSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerPrototypeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerPrototypeStatus) DeepCopyInto(out *WorkerPrototypeStatus) {
	*out = *in
	if in.LastEnsureTime != nil {
		in, out := &in.LastEnsureTime, &out.LastEnsureTime
		*out = (*in).DeepCopy()
	}
	if in.ActiveOperation != nil {
		in, out := &in.ActiveOperation, &out.ActiveOperation
		*out = new(WorkerOperationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerPrototypeStatus.
func (in *WorkerPrototypeStatus) DeepCopy() *WorkerPrototypeStatus {
	if in == nil {
		return nil
	}
	out := new(WorkerPrototypeStatus)
	in.DeepCopyInto(out)
	return out
}
