{
 "title": "Boy's dashboarda",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"prime-service-deployment-.*\",container!=\"\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"prime-service-deployment-.*\",container!=\"\"}/(1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "RPS - HTTP - rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS-1m"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count[2m]))",
     "legendFormat": "RPS-2m"
    },
    {
     "expr": "sum(irate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS-irate"
    }
   ]
  },
  {
   "title": "RPS - Nginx - rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "RPS-1m"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[2m]))",
     "legendFormat": "RPS-2m"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "RPS-irate"
    }
   ]
  },
  {
   "title": "RPS - HTTP/NGINX - diff",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "abs(sum(rate(http_request_duration_seconds_count[1m]))-sum(rate(nginx_ingress_controller_requests[1m])))",
     "legendFormat": "RPS-1m"
    },
    {
     "expr": "abs(sum(rate(http_request_duration_seconds_count[5m]))-sum(rate(nginx_ingress_controller_requests[5m])))",
     "legendFormat": "RPS-5m"
    },
    {
     "expr": "abs(sum(irate(http_request_duration_seconds_count[1m]))-sum(irate(nginx_ingress_controller_requests[1m])))",
     "legendFormat": "RPS-irate"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "P95 - HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"prime-service\"}[1m])))",
     "legendFormat": "P95-1m"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"prime-service\"}[2m])))",
     "legendFormat": "P95-2m"
    }
   ]
  },
  {
   "title": "P95 - ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-backend\"}[1m])))",
     "legendFormat": "P95-1m"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-backend\"}[2m])))",
     "legendFormat": "P95-2m"
    }
   ]
  },
  {
   "title": "Nginx - process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_connections{state=~\"active|writing\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "P95 - HTTP/NGINX - diff",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "abs(histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"prime-service\"}[1m])))-histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-backend\"}[1m]))))",
     "legendFormat": "RPS-1m"
    },
    {
     "expr": "abs(histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"prime-service\"}[2m])))-histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-backend\"}[2m]))))",
     "legendFormat": "RPS-2m"
    },
    {
     "expr": "abs(histogram_quantile(0.99, sum by (le) (irate(http_request_duration_seconds_bucket{service=\"prime-service\"}[1m])))-histogram_quantile(0.95, sum by (le) (irate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"ingress-backend\"}[1m]))))",
     "legendFormat": "RPS-irate"
    }
   ]
  }
 ]
}