apiVersion: autoscaling.my.domain/v1
kind: CustomScaler
metadata:
  labels:
    app.kubernetes.io/name: customer-scaler
    app.kubernetes.io/managed-by: kustomize
  name: customscaler-sample
spec:
  url: "http://localhost:1208"
  deploymentName: prime-service-deployment
