apiVersion: autoscaling.my.domain/v1
kind: CustomScaler
metadata:
  labels:
    app.kubernetes.io/name: customer-scaler
    app.kubernetes.io/managed-by: kustomize
  name: customscaler-sample
spec:
  url: "http://forecasting-service.default.svc.cluster.local:8080/predict-workload"
  deploymentName: prime-service-deployment
  intervalMinutes: 1
  prometheusQuery: 'sum(rate(http_requests_total{job="prime-service"}[2m]))'
  targetMetricName: requests_per_second
