apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-access-log: "true"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Prime service
          - path: /api/prime/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prime-service
                port:
                  number: 8080

          # Text service
          - path: /api/text/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: text-service
                port:
                  number: 8080

          # IO service
          - path: /api/io/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: io-service
                port:
                  number: 8080