# PHẦN 1: HEADER (THÔNG TIN CHUNG)
apiVersion: apps/v1 # Phiên bản API của K8s (Deployment dùng apps/v1)
kind: Deployment # Loại tài nguyên muốn tạo
metadata:
  name: prime-service-deployment # Tên định danh của Deployment này
  labels:
    app: prime-service
spec:
  replicas: 1 # Số lượng Pod muốn chạy (Scale ở đây)

  # KẾT NỐI (SELECTOR) - CỰC KỲ QUAN TRỌNG
  selector:
    matchLabels:
      app: prime-service # "Tôi chỉ quản lý những thằng Pod nào dán nhãn này"
  template:
    # 3.1: Nhãn của Pod (Phải khớp với Selector ở trên)
    metadata:
      labels:
        app: prime-service # <--- Dán cái nhãn này lên trán Pod

    # 3.2: Cấu hình Container (Giống Docker Compose)
    spec:
      containers:
        - name: prime-service-container # Tên của container bên trong Pod
          image: docker.io/boygioi/prime-service:latest # Tên Image (đã build)

          # CỔNG CỦA CONTAINER
          ports:
            - containerPort: 3000 # CHỈ MANG TÍNH CHẤT THÔNG BÁO! Ứng dụng bên trong lắng nghe ở cổng này
          
          resources:
            limits:
              cpu: "600m"      # This forces: 40000 100000
              memory: "128Mi"  # Protects your Nitro from RAM leaks
            requests:
              cpu: "300m"      # Ensures the pod gets its fair share
              memory: "128Mi"