apiVersion: v1
kind: Secret
metadata:
  name: vm-job-secret
  labels:
    app.kubernetes.io/name: custom-scaler
    app.kubernetes.io/component: vm-job
type: Opaque
stringData:
  VULTR_API_KEY: "REPLACE_ME"
  K3S_TOKEN: "REPLACE_ME"
  id_ed25519: |
    REPLACE_WITH_PRIVATE_KEY
  id_ed25519.pub: "REPLACE_WITH_PUBLIC_KEY"
