apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-job-config
  labels:
    app.kubernetes.io/name: custom-scaler
    app.kubernetes.io/component: vm-job
data:
  VULTR_REGION: "xxx"
  VULTR_PLAN: "xxx"
  VULTR_OS_ID: "xxx"
  VULTR_FIREWALL_GROUP_ID: "axxx"
  VULTR_VPC_ID: "xxx"
  VULTR_SSH_KEY_IDS: "xxx"
  VULTR_LOAD_BALANCER_ID: "xxx"
  VULTR_BOOTSTRAP_SSH_USER: "root"
  K3S_URL: "https://10.40.96.3:6443"
  FLANNEL_IFACE_DEFAULT: "enp8s0"
  BOOTSTRAP_SSH_HOST_MODE: "public"
  VULTR_ROOT_PUBLIC_KEY_FILE: "/xxx"
  SSH_OPTS: "-i /var/run/vm-job-secret/id_ed25519 -o StrictHostKeyChecking=accept-new"
