apiVersion: autoscaling.my.domain/v1
kind: CustomScaler
metadata:
  labels:
    app.kubernetes.io/name: custom-scaler
    app.kubernetes.io/managed-by: kustomize
  name: customscaler-sample
spec:
  url: "http://forecasting-service.default.svc.cluster.local:8080/forecast"
  deploymentName: prime-service-deployment
  forecastDeployment: prime-service
  intervalMinutes: 1
  safeRpsPerPod: 16
  safetyFactor: 1.20
  sparePod: 2
  minReplicas: 5
  maxReplicas: 50
  workerPrototype:
    maxBatchSize: 1
